//! Extract links from XML documents. Currently only sitemaps are supported.
use std::sync::LazyLock;

use log::warn;
use regex::Regex;

use crate::types::uri::raw::{RawUri, SpanProvider};

// Static regex for extracting URLs from sitemaps
static SITEMAP_URL_REGEX: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?x)                      # Enable extended mode for whitespace and comments
        <loc>(                      # Match '<loc>'
        (?P<url>[^<]+)              # Capture the URL (anything until the next '<')
        )</loc>                     # Match '</loc>'
        ",
    )
    .expect("XML URL regex should be valid")
});

/// Extract unparsed URL strings from Sitemaps
pub(crate) fn extract_sitemap_xml<S: SpanProvider>(input: &str, span_provider: &S) -> Vec<RawUri> {
    let uris: Vec<RawUri> = SITEMAP_URL_REGEX
        .captures_iter(input)
        .filter_map(|cap| {
            let url = cap.name("url").map(|m| m.as_str().trim())?;

            // Get the position of the entire match (for span information)
            let match_start = cap.get(0)?.start();

            Some(RawUri {
                text: url.to_string(),
                element: Some("loc".to_string()),
                attribute: None,
                span: span_provider.span(match_start),
            })
        })
        .collect();

    if uris.is_empty() {
        warn!("No URLs found in sitemap XML input. Currently, lychee only supports extracting URLs from <loc> elements in sitemaps. If your XML contains links in a different format, please consider submitting a feature request or contributing support for additional XML formats.");
    }

    uris
}

#[cfg(test)]
mod tests {
    use crate::types::uri::raw::SourceSpanProvider;

    use super::*;

    fn extract(input: &str) -> Vec<RawUri> {
        extract_sitemap_xml(input, &SourceSpanProvider::from_input(input))
    }

    #[test]
    fn test_extract_sitemap_links() {
        // Sitemap example generated by mkdocs
        let input = r#"<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
         <loc>https://elastisys.io/welkin/</loc>
         <lastmod>2026-03-04</lastmod>
    </url>
    <url>
         <loc>https://elastisys.io/welkin/architecture/</loc>
         <lastmod>2026-03-04</lastmod>
    </url>
    <url>
         <loc>https://elastisys.io/welkin/glossary/</loc>
         <lastmod>2026-03-04</lastmod>
    </url>
</urlset>"#;

        let links: Vec<RawUri> = extract(input);
        let expected_links = vec![
            "https://elastisys.io/welkin/",
            "https://elastisys.io/welkin/architecture/",
            "https://elastisys.io/welkin/glossary/",
        ];

        assert_eq!(links.len(), 3, "Should extract all URLs");

        for expected_link in expected_links {
            assert!(
                links.iter().any(|u| u.text == expected_link),
                "Should find URL: {expected_link}"
            );
        }

        for link in &links {
            assert_eq!(link.element, Some("loc".to_string()));
            assert_eq!(link.attribute, None);
        }
    }
}
