# See here for image contents: https://github.com/devcontainers/images/blob/v0.4.26/src/rust/.devcontainer/Dockerfile
# [Choice] Debian OS version (use bookworm, or bullseye on local arm64/Apple Silicon): bookworm, buster, bullseye
ARG VARIANT="trixie"
FROM mcr.microsoft.com/vscode/devcontainers/rust:0-${VARIANT}
