[package]
name = "textfrag"
edition = "2021"
version.workspace = true

[dependencies]
fancy-regex = "0.14.0"
html5ever = "0.29.0"
log = "0.4.25"
percent-encoding = "2.3.1"
thiserror = "2.0.11"
url = { version = "2.5.4", features = ["serde"] }
