name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          # Only the input path is passed here.
          #
          # All other options live in `lychee.toml` (which lychee-action
          # auto-loads from the repo root).
          args: .

      - name: Create Issue From File
        if: github.repository_owner == 'lycheeverse' && env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
